#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
nohup $OPENSHIFT_REPO_DIR/diy/oo-install-server.rb $OPENSHIFT_DIY_IP $OPENSHIFT_DATA_DIR $OPENSHIFT_APP_DNS |& /usr/bin/logshifter -tag oo &
